// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Fibonacci.proto

#include "Fibonacci.pb.h"
#include "Fibonacci.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace fibonacci {

static const char* Fibonacci_method_names[] = {
  "/fibonacci.Fibonacci/calculateFibonacci",
};

std::unique_ptr< Fibonacci::Stub> Fibonacci::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Fibonacci::Stub> stub(new Fibonacci::Stub(channel, options));
  return stub;
}

Fibonacci::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_calculateFibonacci_(Fibonacci_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Fibonacci::Stub::calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::fibonacci::FibonacciReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_calculateFibonacci_, context, request, response);
}

void Fibonacci::Stub::async::calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_calculateFibonacci_, context, request, response, std::move(f));
}

void Fibonacci::Stub::async::calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_calculateFibonacci_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>* Fibonacci::Stub::PrepareAsynccalculateFibonacciRaw(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::fibonacci::FibonacciReply, ::fibonacci::FibonacciRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_calculateFibonacci_, context, request);
}

::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>* Fibonacci::Stub::AsynccalculateFibonacciRaw(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsynccalculateFibonacciRaw(context, request, cq);
  result->StartCall();
  return result;
}

Fibonacci::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Fibonacci_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Fibonacci::Service, ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Fibonacci::Service* service,
             ::grpc::ServerContext* ctx,
             const ::fibonacci::FibonacciRequest* req,
             ::fibonacci::FibonacciReply* resp) {
               return service->calculateFibonacci(ctx, req, resp);
             }, this)));
}

Fibonacci::Service::~Service() {
}

::grpc::Status Fibonacci::Service::calculateFibonacci(::grpc::ServerContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace fibonacci

