// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Fibonacci.proto
#ifndef GRPC_Fibonacci_2eproto__INCLUDED
#define GRPC_Fibonacci_2eproto__INCLUDED

#include "Fibonacci.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace fibonacci {

// The fibonacci service definition.
class Fibonacci final {
 public:
  static constexpr char const* service_full_name() {
    return "fibonacci.Fibonacci";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::fibonacci::FibonacciReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fibonacci::FibonacciReply>> AsynccalculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fibonacci::FibonacciReply>>(AsynccalculateFibonacciRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fibonacci::FibonacciReply>> PrepareAsynccalculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::fibonacci::FibonacciReply>>(PrepareAsynccalculateFibonacciRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fibonacci::FibonacciReply>* AsynccalculateFibonacciRaw(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::fibonacci::FibonacciReply>* PrepareAsynccalculateFibonacciRaw(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::fibonacci::FibonacciReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>> AsynccalculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>>(AsynccalculateFibonacciRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>> PrepareAsynccalculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>>(PrepareAsynccalculateFibonacciRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response, std::function<void(::grpc::Status)>) override;
      void calculateFibonacci(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>* AsynccalculateFibonacciRaw(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::fibonacci::FibonacciReply>* PrepareAsynccalculateFibonacciRaw(::grpc::ClientContext* context, const ::fibonacci::FibonacciRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_calculateFibonacci_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status calculateFibonacci(::grpc::ServerContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_calculateFibonacci : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_calculateFibonacci() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_calculateFibonacci() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calculateFibonacci(::grpc::ServerContext* /*context*/, const ::fibonacci::FibonacciRequest* /*request*/, ::fibonacci::FibonacciReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcalculateFibonacci(::grpc::ServerContext* context, ::fibonacci::FibonacciRequest* request, ::grpc::ServerAsyncResponseWriter< ::fibonacci::FibonacciReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_calculateFibonacci<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_calculateFibonacci : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_calculateFibonacci() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::fibonacci::FibonacciRequest* request, ::fibonacci::FibonacciReply* response) { return this->calculateFibonacci(context, request, response); }));}
    void SetMessageAllocatorFor_calculateFibonacci(
        ::grpc::MessageAllocator< ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_calculateFibonacci() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calculateFibonacci(::grpc::ServerContext* /*context*/, const ::fibonacci::FibonacciRequest* /*request*/, ::fibonacci::FibonacciReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* calculateFibonacci(
      ::grpc::CallbackServerContext* /*context*/, const ::fibonacci::FibonacciRequest* /*request*/, ::fibonacci::FibonacciReply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_calculateFibonacci<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_calculateFibonacci : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_calculateFibonacci() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_calculateFibonacci() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calculateFibonacci(::grpc::ServerContext* /*context*/, const ::fibonacci::FibonacciRequest* /*request*/, ::fibonacci::FibonacciReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_calculateFibonacci : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_calculateFibonacci() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_calculateFibonacci() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calculateFibonacci(::grpc::ServerContext* /*context*/, const ::fibonacci::FibonacciRequest* /*request*/, ::fibonacci::FibonacciReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestcalculateFibonacci(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_calculateFibonacci : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_calculateFibonacci() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->calculateFibonacci(context, request, response); }));
    }
    ~WithRawCallbackMethod_calculateFibonacci() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status calculateFibonacci(::grpc::ServerContext* /*context*/, const ::fibonacci::FibonacciRequest* /*request*/, ::fibonacci::FibonacciReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* calculateFibonacci(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_calculateFibonacci : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_calculateFibonacci() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::fibonacci::FibonacciRequest, ::fibonacci::FibonacciReply>* streamer) {
                       return this->StreamedcalculateFibonacci(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_calculateFibonacci() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status calculateFibonacci(::grpc::ServerContext* /*context*/, const ::fibonacci::FibonacciRequest* /*request*/, ::fibonacci::FibonacciReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedcalculateFibonacci(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::fibonacci::FibonacciRequest,::fibonacci::FibonacciReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_calculateFibonacci<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_calculateFibonacci<Service > StreamedService;
};

}  // namespace fibonacci


#endif  // GRPC_Fibonacci_2eproto__INCLUDED
